repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
#    -   id: check-added-large-files
    -   id: mixed-line-ending
    -   id: trailing-whitespace
#-   repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v2.3.0
#    hooks:
#    -   id: no-commit-to-branch
#        args: ['--branch', 'main']
-   repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
    -   id: blacken-docs
#-   repo: https://github.com/PyCQA/flake8
#    rev: 6.1.0
#    hooks:
#    -   id: flake8
#        args:
#            - "--max-line-length=120"
#-   repo: https://github.com/PyCQA/pydocstyle
#    rev: 5.0.2
#    hooks:
#    -   id: pydocstyle
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        args: [ '--profile', 'black' ]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
